server:
  port: 8080

spring:
  application:
    name: aisystem

openai:
  api:
    key: ${OPENAI_API_KEY}

---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.apache.kafka.common.serialization.StringSerializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

      bindings:
        event-in:
          group: aisystem
          destination: labcqrssummarize
          contentType: application/json
          consumer:
            configuration:
              key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
              value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

        event-out:
          destination: labcqrssummarize
          contentType: application/json
          producer:
            configuration:
              key.serializer: org.apache.kafka.common.serialization.StringSerializer
              value.serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

api:
  url:
    aisystem: localhost:8086

server:
  port: 8086

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
          configuration:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.apache.kafka.common.serialization.StringSerializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

      bindings:
        event-in:
          group: aisystem
          destination: labcqrssummarize
          contentType: application/json
          consumer:
            configuration:
              key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
              value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

        event-out:
          destination: labcqrssummarize
          contentType: application/json
          producer:
            configuration:
              key.serializer: org.apache.kafka.common.serialization.StringSerializer
              value.serializer: org.apache.kafka.common.serialization.StringSerializer

api:
  url:
    aisystem: aisystem:8080
